### ISSUE TITLE
welcome screen

### ISSUE THREAD

**Issue by NoelAnnParisi** [KornerShop/Compass-Native#2]
insp: [airbnb](airbnb.com/mobile)

**Comment by ycleptkellan** [comment]
If language pref not in [asyncStorage](https://facebook.github.io/react-native/docs/asyncstorage.html), render welcome screen and store it there + redux store. Else, render map tab in preferred language.

**Comment by ycleptkellan** [comment]
[home screen] (https://www.google.com/imgres?imgurl=https%3A%2F%2Fs-media-cache-ak0.pinimg.com%2Foriginals%2Ff2%2F91%2F58%2Ff2915838a74a4e652a818d6cbd79f51e.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fpin%2F550565123175792110%2F&docid=NTTd18gBBNclNM&tbnid=Z1YLWpao3Vgm_M%3A&vet=10ahUKEwjKrbyDo9DUAhUJLmMKHYiwBH8QMwgxKAowCg..i&w=640&h=1136&itg=1&bih=921&biw=1485&q=airbnb%20mobile%20form&ved=0ahUKEwjKrbyDo9DUAhUJLmMKHYiwBH8QMwgxKAowCg&iact=mrc&uact=8)

**Comment by ycleptkellan** [comment]
we can grab our icons from [expo's icons library](https://expo.github.io/vector-icons/) (simplelineicon 'compass')

**Comment by ycleptkellan** [comment]
remember to add async shtuff back

**Comment by ycleptkellan** [comment]
add orientation lock for this component after we eject out: https://github.com/yamill/react-native-orientation

**Comment by ycleptkellan** [comment]
done
