### ISSUE TITLE
Onboarding Screen

### ISSUE THREAD

**Issue by NoelAnnParisi** [KornerShop/Compass-Native#37]
After the user chooses their language they'll see an onboarding screen that describes what the app allows them to do.

**Comment by ycleptkellan** [comment]
- [carousel](https://github.com/appintheair/react-native-looped-carousel)
- animations
-- [egghead](https://egghead.io/courses/animate-react-native-ui-elements)
-- [egghead1](https://egghead.io/courses/real-world-react-native-animations)
